---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---

Load the required R Libraries and Surppress Messages
    suppressMessages(library(dplyr))
## Warning: package 'dplyr' was built under R version 3.2.5
    suppressMessages(library(ggplot2))
    suppressMessages(library(knitr))
    suppressMessages(library(lubridate))
## Warning: package 'lubridate' was built under R version 3.2.5
    suppressMessages(library(scales))
Load Dataset and Transform Date
    setwd("C:/Users/ian/R/Rprogramming/assignment31")
    activity <- read.csv("activity.csv",header = TRUE, sep = ',')
    activity$date <- ymd(activity$date)
    steps <- activity %>% 
        filter(!is.na(steps)) %>%
            group_by(date) %>% 
                summarize(steps = sum(steps))
What is mean total number of steps taken per day?
Plot Histogram of the Total Number of Steps Taken per Day
    ggplot(steps, aes(x = steps)) +
        geom_histogram(fill = "mistyrose3", col=I("black"), binwidth = 1000) +
        labs(title = "Total Number of Steps Taken Each Day",
             x = "Steps per Day", 
             y = "Occurances")


Calculate and report the mean and median of the total number of steps taken per day
    mean.steps <- round(mean(steps$steps, na.rm=TRUE))
    median.steps <- round(median(steps$steps, na.rm=TRUE))
    paste("The Mean number of steps is",mean.steps,"and the Median is",median.steps)
## [1] "The Mean number of steps is 10766 and the Median is 10765"
What is the average daily activity pattern?
    activity$interval <- as.POSIXct(strptime(sprintf("%04d", activity$interval), "%H%M"))
    interval <- activity %>% 
        filter(!is.na(steps)) %>% 
            group_by(interval) %>% 
                summarize(steps = mean(steps))
Make a time-plot of the 5-minute interval and average number of steps taken, averaged across all days
    ggplot(interval, aes(x=interval, y=steps)) +
        geom_line(color = "mistyrose4") +
        scale_x_datetime(breaks = date_breaks("2 hour"), 
            labels = date_format("%H:%M"),
            limits = c(interval$Interval[1], interval$Interval[288])) +
        labs(title = "Average Number of Steps taken (Averaged Across All Days)", 
             x = "Time of Day", 
             y = "Average Steps")


Which 5-minute interval, on average across all the days, contains the maximum number of steps?
    max.interval <- interval[which.max(interval$steps),]
    paste("The interval with the maximum number of steps is",
        round(max.interval$steps[1]), "at",
        strftime(max.interval$interval[1], format="%H:%M:%S"))
## [1] "The interval with the maximum number of steps is 206 at 08:35:00"
There are a number of days/intervals where there are missing values (coded as NA). The presence of such days may introduce bias into some calculations or summaries of the data.

Calculate and report the total number of missing values in the dataset
    missing.steps <- sum(is.na(activity$steps))
    paste("The number of missing values in the dataset is",missing.steps)
## [1] "The number of missing values in the dataset is 2304"
Devise a strategy for filling in all of the missing values in the dataset.
    tofill.activity <- activity
    missing.activity <- is.na(tofill.activity$steps)
    mean.interval <- tapply(tofill.activity$steps,
        tofill.activity$interval, 
        mean, na.rm=TRUE, simplify=TRUE)
Create a new dataset (equal to the original) but with the missing data filled in.
    tofill.activity$steps[missing.activity] <- mean.interval[as.character(tofill.activity$interval[missing.activity])]
Make a histogram of the total number of steps taken each day
    filled_steps <- tofill.activity %>%
        filter(!is.na(steps)) %>% 
            group_by(date) %>% 
                summarize(steps = sum(steps))
    ggplot(filled_steps, aes(x = steps)) +
        geom_histogram(fill = "mistyrose3",colour="Black",binwidth = 1000) +
        labs(title = "Total Number of Steps Each Day (missing values replaced)", 
        x = "Steps per day",
        y = "Occurances")


Calculate and report the mean and median total number of steps taken per day
    mean.steps <- round(mean(filled_steps$steps, na.rm=TRUE))
    median.steps <- round(median(filled_steps$steps, na.rm=TRUE))
    paste("The Mean number of steps is",mean.steps,"and the Median is",median.steps)
## [1] "The Mean number of steps is 10766 and the Median is 10766"
Do these values differ from the estimates from the first part of the assignment?
    imputed <- mutate(tofill.activity, 
        weektype = ifelse(weekdays(tofill.activity$date) == "Saturday" |
        weekdays(tofill.activity$date) == "Sunday", "Weekend", "Weekday"))
    imputed$weektype <- as.factor(imputed$weektype)
    imputed.full <- imputed %>%
        group_by(interval, weektype) %>%
            summarise(steps = mean(steps)) 
    ggplot(imputed.full, aes(x=interval, y=steps, color = weektype)) +
        geom_line(color = "mistyrose4") +
        facet_wrap(~weektype, ncol = 1, nrow=2)+
        scale_x_datetime(breaks = date_breaks("2 hour"),
            labels = date_format("%H:%M"),
            limits = c(imputed.full$Interval[1],
            imputed.full$Interval[288])) +
      labs(title = "Average Number of Steps taken (Weekdays vs. Weekends)",
            x = "Time of Day", 
            y = "Average Steps")
